version: "3"

tasks:
  web:install:
    desc: Install frontend dependencies
    cmds:
      - npm install --prefix ./web

  web:dev:
    desc: Start Vite dev server
    cmds:
      - npm run dev --prefix ./web

  web:build:
    desc: Build frontend assets for embed.FS
    cmds:
      - npm run build --prefix ./web

  run:
    desc: Build frontend assets and run app
    cmds:
      - npm run build --prefix ./web
      - go run ./main.go

  dev:
    desc: Start Air hot-reload (builds frontend before each rebuild)
    cmds:
      - air -c .air.toml
